### PR TITLE
Add command for stopping and starting short/long break

### PR DESCRIPTION
**Pull request by grassbl8d**
Add command for starting and stopping break (long or short)

### CODE REVIEW

**Comment by kzhovn** [comment]
As written, Start Long Break does the exact same thing as Start Short Break. If you want a command to start a long break, you would need to change the logic to allow for a long break to be started at arbitrary times, not just after the set number of pomos have passed.

Separately, I'm not sure I see the point of these commands - what's your use case?

**Comment by grassbl8d** [comment]
Sorry, messed up. just change it to breaks.

Well a common use case is a tendency to extend or miss out on the breaks.

So I want to start and stop the breaks manually.

I'm also looking at a mode where in we coudl track extended pomodoro not just the 25 minutes and stop watch mode. 

Thanks.

**Comment by kzhovn** [comment]
Do you want starting a long break manually to reset the long break counter? If so, your code doesn't do that; this has the effect of basically inserting a break into the flow and then continuing with the next pomo as if that break didn't happen.

**Comment by grassbl8d** [comment]
Actually it's not my intention to reset th counter. However, I can add code to reset i but in the use case I'm thinking of I don't really want to reset it. 

My intention is just to start a break manually  

Maybe we can add a visual indicator for Consistent pomodoros beside the timer in the status bar. and add another Pomodoro color for 4 straight ones. A golden tomato perhaps.

**Comment by kzhovn** [comment]
The visual indicator seems unnecessary.

I think right now you want some pretty different things out of this plugin than what works for me, especially with that new mode you mentioned. It might be better for you to make your own fork with the changes you want here and in your other PR. I'd be happy to help you set that up if you have any issues with that.

**Comment by grassbl8d** [comment]
Nah I'll work with what you think. I just suggested this becaise I also used forest app for ios android. These are its features. You can take a look at it. https://www.forestapp.cc/

**Pull request closed without merging**
