### PR TITLE
Show system notifications, based on a setting

### PR DESCRIPTION
**Pull request by cbos**
@kzhovn, this PR adds the option of system notification.
I like to have that and this is also requested in #38 

The implementation of the system notification the same as with the Obsidian Reminder plugin:
https://github.com/uphy/obsidian-reminder/blob/master/src/ui/reminder.ts#L24

Which is based on the Electron documentation:
https://www.electronjs.org/docs/latest/tutorial/notifications   
https://www.electronjs.org/docs/latest/api/notification

### CODE REVIEW

**Comment by kzhovn** [comment]
Thank you @cbos , and sorry for the delay!

**Comment by kzhovn** [comment]
Hmm. I'm not getting system notifications on my computer. This might be an effect of my system (Ubuntu + i3). Can I ask what OS you tested this on?

**Comment by cbos** [comment]
I have tested it on MacOS, there is it working as expected.
I have developed it on Ubuntu and there is was working fine as well.

**Comment by kzhovn** [comment]
Swapped to regular old Ubuntu without i3 and everything is working fine, so whatever the issue is it's i3's fault. I might try debugging later but that's rare enough I'm happy to merge anyway.

**Comment by kzhovn** [comment]
Okay, should be live, let me know if there are any issues.

**Comment by cbos** [comment]
Thanks a lot 👍!

**Pull request merged**
